#!/usr/bin/env node
/**
 * Reads scripts/india-states-source.svg + scripts/wikimedia-id-map.json
 * and outputs src/map/statePaths.ts containing STATE_PATHS: Record<string, string>
 *
 * Run with: npx tsx scripts/extract-svg-paths.ts
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { DOMParser } from '@xmldom/xmldom';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const svgContent = readFileSync(join(__dirname, 'india-states-source.svg'), 'utf8');
const mapping: Record<string, string[]> = JSON.parse(
  readFileSync(join(__dirname, 'wikimedia-id-map.json'), 'utf8')
);

const parser = new DOMParser();
const doc = parser.parseFromString(svgContent, 'image/svg+xml');

function getElementById(id: string): Element | null {
  const all = doc.getElementsByTagName('*');
  for (let i = 0; i < all.length; i++) {
    const el = all[i] as Element;
    if (el.getAttribute && el.getAttribute('id') === id) return el;
  }
  return null;
}

function extractDFromElement(el: Element): string {
  const tag = el.tagName?.toLowerCase();

  if (tag === 'path') {
    return el.getAttribute('d') ?? '';
  }

  if (tag === 'use') {
    const href =
      el.getAttribute('href') ??
      el.getAttributeNS('http://www.w3.org/1999/xlink', 'href') ??
      '';
    const refId = href.startsWith('#') ? href.slice(1) : href;
    if (!refId) return '';
    const ref = getElementById(refId);
    return ref ? extractDFromElement(ref as Element) : '';
  }

  if (tag === 'g') {
    const parts: string[] = [];
    const children = el.childNodes;
    for (let i = 0; i < children.length; i++) {
      const child = children[i] as Element;
      if (child.tagName) {
        const d = extractDFromElement(child);
        if (d) parts.push(d);
      }
    }
    return parts.join(' ');
  }

  return '';
}

const statePaths: Record<string, string> = {};
const warnings: string[] = [];

for (const [stateId, svgIds] of Object.entries(mapping)) {
  const dParts: string[] = [];

  for (const svgId of svgIds) {
    const el = getElementById(svgId);
    if (!el) {
      warnings.push(`SVG element id="${svgId}" not found (state ${stateId})`);
      continue;
    }
    const d = extractDFromElement(el as Element);
    if (d) {
      dParts.push(d.trim());
    } else {
      warnings.push(`No path data for id="${svgId}" (state ${stateId})`);
    }
  }

  if (dParts.length > 0) {
    statePaths[stateId] = dParts.join(' ');
  }
}

const missing = Object.keys(mapping).filter((id) => !statePaths[id]);

const output = `// Generated by scripts/extract-svg-paths.ts — do not edit manually\nexport const STATE_PATHS: Record<string, string> = ${JSON.stringify(statePaths, null, 2)};\n`;

writeFileSync(join(root, 'src', 'map', 'statePaths.ts'), output);

console.log(`✓ Generated STATE_PATHS with ${Object.keys(statePaths).length} entries`);

if (warnings.length) {
  console.warn('\nWarnings:');
  warnings.forEach((w) => console.warn('  ⚠', w));
}

if (missing.length) {
  console.error(`\n✗ Missing states: ${missing.join(', ')}`);
  process.exit(1);
} else {
  console.log('✓ All 36 states and UTs present');
}
